spring:
  redis:
    host: 192.168.60.16
    # 连接超时时间（记得添加单位，Duration）
    timeout: 10000ms
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1ms
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
    sentinel:
      master: mymaster
      nodes:
        - 10.16.61.21:26379
        - 10.16.61.22:26379
        - 10.16.61.23:26379
  cache:
    couchbase:
      # 默认超时时间
      expiration: "10m"
logging:
  level:
    root: info
