server:
  port: 8080
spring:
  application:
    name: admin-client
  boot:
    admin:
      client:
        url: http://localhost:8000
        username: riger
        password: riger
        # 实际部署使用的时候可能获取的应用host不正确,需要手动指定
        instance:
          service-base-url: http://localhost:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

logging:
  file:
    name: logs/client.log # 要配置log文件名,才能在Admin里查看log